// THIS FILE IS AUTOGENERATED. MODIFICATIONS WILL BE LOST!

package hs.saga.config.rest.integration.custas.customerassessment.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
// import org.openapitools.jackson.nullable.JsonNullable;


/**
 * 고객평가 요청
 */
@Schema(description = "고객평가 요청")
@javax.annotation.Generated(value = "de.knowis.cp.openapigenerator.springdoc.SpringSpringdocGenerator", date = "2022-10-29T01:40:14.183869Z[GMT]")
public class CustomerAssessmentRequest   {
  @JsonProperty("customerId")
  private String customerId;

  @JsonProperty("productCode")
  private String productCode;

  public CustomerAssessmentRequest customerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

  /**
   * 고객ID
   * @return customerId
  */
  @Schema(name="customerId", description = "고객ID")


  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public CustomerAssessmentRequest productCode(String productCode) {
    this.productCode = productCode;
    return this;
  }

  /**
   * 상품코드
   * @return productCode
  */
  @Schema(name="productCode", description = "상품코드")


  public String getProductCode() {
    return productCode;
  }

  public void setProductCode(String productCode) {
    this.productCode = productCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerAssessmentRequest customerAssessmentRequest = (CustomerAssessmentRequest) o;
    return Objects.equals(this.customerId, customerAssessmentRequest.customerId) &&
        Objects.equals(this.productCode, customerAssessmentRequest.productCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerId, productCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerAssessmentRequest {\n");
    
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    productCode: ").append(toIndentedString(productCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

