// THIS FILE IS AUTOGENERATED. MODIFICATIONS WILL BE LOST!

package hs.saga.config.rest.integration.custas.customerassessment.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
// import org.openapitools.jackson.nullable.JsonNullable;


/**
 * 고객평가 응답
 */
@Schema(description = "고객평가 응답")
@javax.annotation.Generated(value = "de.knowis.cp.openapigenerator.springdoc.SpringSpringdocGenerator", date = "2022-10-29T01:40:14.183869Z[GMT]")
public class CustomerAssessmentResponse   {
  @JsonProperty("status")
  private String status;

  @JsonProperty("message")
  private String message;

  @JsonProperty("grade")
  private String grade;

  public CustomerAssessmentResponse status(String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
  */
  @Schema(name="status", description = "")


  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public CustomerAssessmentResponse message(String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
  */
  @Schema(name="message", description = "")


  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public CustomerAssessmentResponse grade(String grade) {
    this.grade = grade;
    return this;
  }

  /**
   * Get grade
   * @return grade
  */
  @Schema(name="grade", description = "")


  public String getGrade() {
    return grade;
  }

  public void setGrade(String grade) {
    this.grade = grade;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerAssessmentResponse customerAssessmentResponse = (CustomerAssessmentResponse) o;
    return Objects.equals(this.status, customerAssessmentResponse.status) &&
        Objects.equals(this.message, customerAssessmentResponse.message) &&
        Objects.equals(this.grade, customerAssessmentResponse.grade);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, message, grade);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerAssessmentResponse {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    grade: ").append(toIndentedString(grade)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

