// THIS FILE IS AUTOGENERATED. MODIFICATIONS WILL BE LOST!

package hs.saga.config.rest.integration.custas.entity;

import com.kbstar.saga.sagadpoffr.sdk.domain.annotation.Domain;
import com.kbstar.saga.sagadpoffr.sdk.domain.entity.EntityBase;
import org.springframework.data.annotation.TypeAlias;

import javax.persistence.Embeddable;
import javax.persistence.MappedSuperclass;

/**
 * Provide implementation class for RetrieveCustChkRsultInput root entity.
 *
 * @Generated
 *
 */
@Domain(name = "custas")
@TypeAlias("custas:RetrieveCustChkRsult_Input")
@Embeddable
@MappedSuperclass

public  class RetrieveCustChkRsultInputEntity extends EntityBase implements RetrieveCustChkRsultInput {

  public RetrieveCustChkRsultInputEntity(){}

  protected String customerId;
  protected String productCode;
  RetrieveCustChkRsultInputEntity(RetrieveCustChkRsultInputBuilder builder) {
    
    this.customerId = builder.customerId;
    this.productCode = builder.productCode;
    
  }

 
  public static class RetrieveCustChkRsultInputBuilder {
    
    private String customerId;
    private String productCode;
    
    public RetrieveCustChkRsultInputEntity build() {
      return new RetrieveCustChkRsultInputEntity(this);
    }
    
    public RetrieveCustChkRsultInputBuilder setCustomerId(String customerId) {
      this.customerId = customerId;
      return this;
    }
    public RetrieveCustChkRsultInputBuilder setProductCode(String productCode) {
      this.productCode = productCode;
      return this;
    }
    
  }
  
  public String getCustomerId(){
    return  customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }
  public String getProductCode(){
    return  productCode;
  }

  public void setProductCode(String productCode) {
    this.productCode = productCode;
  }
}
