// THIS FILE IS AUTOGENERATED. MODIFICATIONS WILL BE LOST!

package hs.saga.config.rest.integration.custas.entity;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.kbstar.saga.sagadpoffr.sdk.domain.entity.Entity;

/**
 * Provide an interface for RetrieveCustChkRsultInput root entity.
 * 
 *
 * @Generated
 *
 */
@JsonDeserialize(as = RetrieveCustChkRsultInputEntity.class)

public  interface RetrieveCustChkRsultInput extends Entity {
  
  String getCustomerId();
  void setCustomerId(String customerId);
  String getProductCode();
  void setProductCode(String productCode);
}
