// THIS FILE IS AUTOGENERATED. MODIFICATIONS WILL BE LOST!

package hs.saga.config.rest.integration.custas.entity;

import com.kbstar.saga.sagadpoffr.sdk.domain.annotation.Domain;
import com.kbstar.saga.sagadpoffr.sdk.domain.entity.EntityBase;
import org.springframework.data.annotation.TypeAlias;

import javax.persistence.Embeddable;
import javax.persistence.MappedSuperclass;

/**
 * Provide implementation class for RetrieveCustChkRsultOutput root entity.
 *
 * @Generated
 *
 */
@Domain(name = "custas")
@TypeAlias("custas:RetrieveCustChkRsult_Output")
@Embeddable
@MappedSuperclass

public  class RetrieveCustChkRsultOutputEntity extends EntityBase implements RetrieveCustChkRsultOutput {

  public RetrieveCustChkRsultOutputEntity(){}

  protected String status;
  protected String message;
  protected String grade;
  RetrieveCustChkRsultOutputEntity(RetrieveCustChkRsultOutputBuilder builder) {
    
    this.status = builder.status;
    this.message = builder.message;
    this.grade = builder.grade;
    
  }

 
  public static class RetrieveCustChkRsultOutputBuilder {
    
    private String status;
    private String message;
    private String grade;
    
    public RetrieveCustChkRsultOutputEntity build() {
      return new RetrieveCustChkRsultOutputEntity(this);
    }
    
    public RetrieveCustChkRsultOutputBuilder setStatus(String status) {
      this.status = status;
      return this;
    }
    public RetrieveCustChkRsultOutputBuilder setMessage(String message) {
      this.message = message;
      return this;
    }
    public RetrieveCustChkRsultOutputBuilder setGrade(String grade) {
      this.grade = grade;
      return this;
    }
    
  }
  
  public String getStatus(){
    return  status;
  }

  public void setStatus(String status) {
    this.status = status;
  }
  public String getMessage(){
    return  message;
  }

  public void setMessage(String message) {
    this.message = message;
  }
  public String getGrade(){
    return  grade;
  }

  public void setGrade(String grade) {
    this.grade = grade;
  }
}
