demo:
  stock-service-hostname: 10.17.211.52
  stock-service-port: 8380
  order-service-hostname: 10.17.211.52
  order-service-port: 8280
  assessment-service-hostname: 10.17.211.52
  assessment-service-port: 9102


server:
  port: 9101 #0 #${random.int(10000,51000)}

camel:
  health:
    enabled: false
    indicator:
      enabled: true

  component:
    servlet:
      mapping:
        context-path: /camel/*

  service:
    lra:
      enabled: true
      coordinator-url: http://10.17.211.52:8080
      #참가자 SAGA-APP
      local-participant-url: http://10.17.211.52:9101/camel

spring:
  profiles.active: local
  application:
    name: DepositOffer

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:tcp://localhost/~/testdb`
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        #implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#  datasource:
#    url: jdbc:mysql://localhost:3306/hosuk?autoReconnect=true
#    username: hosuk
#    password: hosuk
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#        #implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
#        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
#        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#logging.level.org.hibernate.type.descriptor.sql: trace
logging.level:
#  org.springframework: debug
  org.hibernate.type.descriptor.sql: debug
