// THIS FILE IS AUTOGENERATED. MODIFICATIONS WILL BE LOST!

package hs.saga.config.rest.integration.error;

/**
 * Error class to throw when Api Binding is not found
 * @Generated
 *
 */
public class ApiBindingNotFound extends RuntimeException {


  private static final long serialVersionUID = 5376990834506619787L;

  public ApiBindingNotFound(String message) {
    super(message);
  }

}
