// THIS FILE IS AUTOGENERATED. MODIFICATIONS WILL BE LOST!

package hs.saga.config.rest.integration.config;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;

@Configuration
@ConfigurationProperties("de.knowis.cp.oidc")
public class AccessTokenConfiguration {

  private String clientRegistrationId;

  public String getClientRegistrationId() {
    return clientRegistrationId;
  }

  public void setClientRegistrationId(String clientRegistrationId) {
    this.clientRegistrationId = clientRegistrationId;
  }
}
