// THIS FILE IS AUTOGENERATED. MODIFICATIONS WILL BE LOST!

package hs.saga.config.rest.integration.config;

import hs.saga.config.rest.integration.model.ApiBinding;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;

import java.util.HashMap;
import java.util.Map;

@Configuration
@ConfigurationProperties("de.cp.consumer.api.binding")
public class BindingProperties {

  private Map<String, ApiBinding> bindingProperties = new HashMap<>();

  public Map<String, ApiBinding> getBindingProperties() {
    return bindingProperties;
  }

  public void setBindingProperties(Map<String, ApiBinding> bindingProperties) {
    this.bindingProperties = bindingProperties;
  }

}
