// THIS FILE IS AUTOGENERATED. MODIFICATIONS WILL BE LOST!

package hs.saga.config.rest.integration.facade;

import com.kbstar.saga.sagadpoffr.sdk.integration.custas.facade.CustasEntityBuilder;
import org.springframework.stereotype.Component;

/**
 * Provide access to all Entity Builder facades.
 *
 * @Generated
 *
 */
@Component
public class IntegrationEntityBuilder {

  protected CustasEntityBuilder custas;



  public IntegrationEntityBuilder(CustasEntityBuilder custas) {
   
   this.custas = custas;
  }


  public CustasEntityBuilder getCustas() {
    return custas;
  }

  public void setCustas(CustasEntityBuilder custas) {
    this.custas = custas;
  }


}
