// THIS FILE IS AUTOGENERATED. MODIFICATIONS WILL BE LOST!

package hs.saga.config.rest.integration.facade;

import com.kbstar.saga.sagadpoffr.sdk.integration.custas.facade.CustasService;
import org.springframework.stereotype.Component;

/**
 * Provide access to all Service facades.
 *
 * @Generated
 *
 */
@Component
public class IntegrationService {

  protected CustasService custas;



  public IntegrationService(CustasService custas) {
   
   this.custas = custas;
  }


  public CustasService getCustas() {
    return custas;
  }

  public void setCustas(CustasService custas) {
    this.custas = custas;
  }


}
