// THIS FILE IS AUTOGENERATED. MODIFICATIONS WILL BE LOST!

package hs.saga.config.rest.integration.model;

import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.HashMap;
import java.util.Map;

/**
 * This class represents API Binding
 * @Generated
 *
 */
public class ApiBinding {

  @JsonProperty(value = "url")
  private String url;

  @JsonProperty(value = "ca_cert")
  private String caCert;

  @JsonProperty("k5_propagate_security_token")
  private boolean k5PropagateSecurityToken;

  private Map<String, Object> additionalProperties = new HashMap<>();

  public String getUrl() {
    return url;
  }

  public String getCaCert() {
    return caCert;
  }

  public boolean isK5PropagateSecurityToken() {
    return k5PropagateSecurityToken;
  }

  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public void setCaCert(String caCert) {
    this.caCert = caCert;
  }

  public void setK5PropagateSecurityToken(boolean k5PropagateSecurityToken) {
    this.k5PropagateSecurityToken = k5PropagateSecurityToken;
  }

  public void setAdditionalProperties(Map<String, Object> additionalProperties) {
    this.additionalProperties = additionalProperties;
  }

  @JsonAnySetter
  void setAdditionalProperties(String key, Object value) {
    additionalProperties.put(key, value);
  }
}
