// THIS FILE IS AUTOGENERATED. MODIFICATIONS WILL BE LOST!

package hs.saga.config.rest.integration.custas.facade;

import org.springframework.stereotype.Component;

/**
 * Provide access to all Service facades.
 *
 * @Generated
 *
 */
@Component
public class CustasService {


}
