// THIS FILE IS AUTOGENERATED. MODIFICATIONS WILL BE LOST!

package hs.saga.config.rest.integration.custas.facade;

import com.kbstar.saga.sagadpoffr.sdk.integration.custas.entity.RetrieveCustChkRsultInputEntity.RetrieveCustChkRsultInputBuilder;
import com.kbstar.saga.sagadpoffr.sdk.integration.custas.entity.RetrieveCustChkRsultOutputEntity.RetrieveCustChkRsultOutputBuilder;
import org.springframework.stereotype.Component;

/**
 * Provide a facade for all custas entity builders.
 *
 * @Generated
 *
 */
@Component
public class CustasEntityBuilder {

  public RetrieveCustChkRsultInputBuilder getRetrieveCustChkRsultInput() {
    return new RetrieveCustChkRsultInputBuilder();
  }

  public RetrieveCustChkRsultOutputBuilder getRetrieveCustChkRsultOutput() {
    return new RetrieveCustChkRsultOutputBuilder();
  }

}
